// Fixed-point (8.8) raycaster — optimized for no-FPU targets
//
// Intercept-based ray marching with precomputed lookup tables.
// No floating-point, no division at runtime. All trig via g_sin/g_cos/
// g_tan/g_cotan tables generated by tools/precalculator.c.
//
// Coordinate system and fixed-point encoding:
//
//            North (512, -Y)
//                 ▲
//                 │
//   West (768) ◄──┼──► East (256, +X)
//                 │
//                 ▼
//            South (0, +Y)
//
//   playerA increases: South(0) → East(256) → North(512) → West(768)
//                    = counter-clockwise in world coordinates
//
//   Position: 8.8 fixed-point — upper 8 bits = tile, lower 8 = sub-tile
//   Angle:    0–1023 = full circle (256 per quadrant)
//
//   Ray marching: separate vertical (X-boundary) and horizontal
//   (Y-boundary) intercept walks, interleaved by tile crossing order.
//
//   Distance projection (fisheye correction):
//     dist = ΔY·cos(playerA) + ΔX·sin(playerA)
//
//   Hit labels:
//     HorizontalHit → Y-boundary crossing → WALL_SOUTH or WALL_NORTH
//     VerticalHit   → X-boundary crossing → WALL_EAST  or WALL_WEST

#include "raycaster_fixed.h"

#include <stdbool.h>
#include <stdlib.h>

#include "raycaster_data.h"
#include "raycaster_tables.h"

typedef struct {
    uint16_t playerX;
    uint16_t playerY;
    int16_t playerA;
    uint8_t viewQuarter;
    uint8_t viewAngle;
} RayCasterFixed;

static void RayCasterFixedStart(RayCaster *rayCaster,
                                uint16_t playerX,
                                uint16_t playerY,
                                int16_t playerA);
static void RayCasterFixedTrace(RayCaster *rayCaster,
                                uint16_t screenX,
                                uint8_t *screenY,
                                uint8_t *textureNo,
                                uint8_t *textureX,
                                uint16_t *textureY,
                                uint16_t *textureStep);
static void RayCasterFixedDestruct(RayCaster *rayCaster);

RayCaster *RayCasterFixedConstruct(void)
{
    RayCaster *rayCaster = RayCasterConstruct();
    if (!rayCaster)
        return NULL;
    RayCasterFixed *rayCasterFixed = malloc(sizeof(RayCasterFixed));
    if (!rayCasterFixed) {
        rayCaster->Destruct(rayCaster);
        return NULL;
    }
    rayCaster->derived = rayCasterFixed;

    rayCaster->Start = RayCasterFixedStart;
    rayCaster->Trace = RayCasterFixedTrace;
    rayCaster->Destruct = RayCasterFixedDestruct;

    return rayCaster;
}

// (v × f) >> 8 — unsigned 8.8 fixed-point multiply
static uint16_t RayCasterFixedMulU(uint8_t v, uint16_t f)
{
    const uint8_t f_h = f >> 8;
    const uint8_t f_l = f % 256;
    const uint16_t hm = v * f_h;
    const uint16_t lm = v * f_l;
    return hm + (lm >> 8);
}

static int16_t RayCasterFixedMulS(uint8_t v, int16_t f)
{
    const uint16_t uf = RayCasterFixedMulU(v, (uint16_t) ABS(f));
    if (f < 0) {
        return -(int16_t) uf;
    }
    return uf;
}

static inline int16_t RayCasterFixedAbsTan(uint8_t quarter,
                                           uint8_t angle,
                                           const uint16_t *lookupTable)
{
    if (quarter & 1) {
        return LOOKUP16(lookupTable, INVERT(angle));
    }
    return LOOKUP16(lookupTable, angle);
}

static int16_t RayCasterFixedMulTan(uint8_t value,
                                    bool inverse,
                                    uint8_t quarter,
                                    uint8_t angle,
                                    const uint16_t *lookupTable)
{
    uint8_t signedValue = value;
    if (inverse) {
        if (value == 0) {
            if (quarter % 2 == 1) {
                return -RayCasterFixedAbsTan(quarter, angle, lookupTable);
            }
            return RayCasterFixedAbsTan(quarter, angle, lookupTable);
        }
        signedValue = INVERT(value);
    }
    if (signedValue == 0) {
        return 0;
    }
    if (quarter % 2 == 1) {
        return -RayCasterFixedMulU(signedValue,
                                   LOOKUP16(lookupTable, INVERT(angle)));
    }
    return RayCasterFixedMulU(signedValue, LOOKUP16(lookupTable, angle));
}

static void RayCasterFixedLookupHeight(uint16_t distance,
                                       uint8_t *height,
                                       uint16_t *step)
{
    if (distance >= 256) {
        const uint16_t ds = distance >> 3;
        if (ds >= 256) {
            *height = LOOKUP8(g_farHeight, 255) - 1;
            *step = LOOKUP16(g_farStep, 255);
        } else {
            *height = LOOKUP8(g_farHeight, ds);
            *step = LOOKUP16(g_farStep, ds);
        }
    } else {
        *height = LOOKUP8(g_nearHeight, distance);
        *step = LOOKUP16(g_nearStep, distance);
    }
}

static void RayCasterFixedCalculateDistance(uint16_t rayX,
                                            uint16_t rayY,
                                            uint16_t rayA,
                                            int16_t *deltaX,
                                            int16_t *deltaY,
                                            uint8_t *textureNo,
                                            uint8_t *textureX)
{
    int8_t tileStepX = 0;
    int8_t tileStepY = 0;
    int16_t interceptX = rayX;
    int16_t interceptY = rayY;

    const uint8_t quarter = rayA >> 8;
    const uint8_t angle = rayA % 256;
    const uint8_t offsetX = rayX % 256;
    const uint8_t offsetY = rayY % 256;

    uint8_t tileX = rayX >> 8;
    uint8_t tileY = rayY >> 8;
    int16_t hitX;
    int16_t hitY;
    const uint16_t maxSteps = MapWidth() + MapHeight() + 1;

    if (angle == 0) {
        switch (quarter % 2) {
        case 0:
            tileStepX = 0;
            tileStepY = quarter == 0 ? 1 : -1;
            if (tileStepY == 1) {
                interceptY -= 256;
            }
            for (uint16_t i = 0; i < maxSteps; i++) {
                tileY += tileStepY;
                if (MapIsWall(tileX, tileY)) {
                    goto HorizontalHit;
                }
            }
            goto HorizontalHit; /* safety fallback */
        case 1:
            tileStepY = 0;
            tileStepX = quarter == 1 ? 1 : -1;
            if (tileStepX == 1) {
                interceptX -= 256;
            }
            for (uint16_t i = 0; i < maxSteps; i++) {
                tileX += tileStepX;
                if (MapIsWall(tileX, tileY)) {
                    goto VerticalHit;
                }
            }
            goto VerticalHit; /* safety fallback */
        }
    } else {
        int16_t stepX = 0;
        int16_t stepY = 0;

        switch (quarter) {
        case 0:
        case 1:
            tileStepX = 1;
            interceptY +=
                RayCasterFixedMulTan(offsetX, true, quarter, angle, g_cotan);
            interceptX -= 256;
            stepX = RayCasterFixedAbsTan(quarter, angle, g_tan);
            break;
        case 2:
        case 3:
            tileStepX = -1;
            interceptY -=
                RayCasterFixedMulTan(offsetX, false, quarter, angle, g_cotan);
            stepX = -RayCasterFixedAbsTan(quarter, angle, g_tan);
            break;
        }

        switch (quarter) {
        case 0:
        case 3:
            tileStepY = 1;
            interceptX +=
                RayCasterFixedMulTan(offsetY, true, quarter, angle, g_tan);
            interceptY -= 256;
            stepY = RayCasterFixedAbsTan(quarter, angle, g_cotan);
            break;
        case 1:
        case 2:
            tileStepY = -1;
            interceptX -=
                RayCasterFixedMulTan(offsetY, false, quarter, angle, g_tan);
            stepY = -RayCasterFixedAbsTan(quarter, angle, g_cotan);
            break;
        }

        for (uint16_t i = 0; i < maxSteps; i++) {
            while ((tileStepY == 1 && (interceptY >> 8 < tileY)) ||
                   (tileStepY == -1 && (interceptY >> 8 >= tileY))) {
                tileX += tileStepX;
                if (MapIsWall(tileX, tileY)) {
                    goto VerticalHit;
                }
                interceptY += stepY;
            }
            while ((tileStepX == 1 && (interceptX >> 8 < tileX)) ||
                   (tileStepX == -1 && (interceptX >> 8 >= tileX))) {
                tileY += tileStepY;
                if (MapIsWall(tileX, tileY)) {
                    goto HorizontalHit;
                }
                interceptX += stepX;
            }
        }
        goto VerticalHit; /* safety fallback */
    }

HorizontalHit:
    hitX = interceptX + (tileStepX == 1 ? 256 : 0);
    hitY = (tileY << 8) + (tileStepY == -1 ? 256 : 0);
    *textureNo = (tileStepY == 1) ? WALL_SOUTH : WALL_NORTH;
    *textureX = interceptX & 0xFF;
    goto WallHit;

VerticalHit:
    hitX = (tileX << 8) + (tileStepX == -1 ? 256 : 0);
    hitY = interceptY + (tileStepY == 1 ? 256 : 0);
    *textureNo = (tileStepX == 1) ? WALL_EAST : WALL_WEST;
    *textureX = interceptY & 0xFF;
    goto WallHit;

WallHit:
    *deltaX = hitX - rayX;
    *deltaY = hitY - rayY;
}

static void RayCasterFixedStart(RayCaster *rayCaster,
                                uint16_t playerX,
                                uint16_t playerY,
                                int16_t playerA)
{
    RayCasterFixed *self = rayCaster->derived;
    self->viewQuarter = playerA >> 8;
    self->viewAngle = playerA % 256;
    self->playerX = playerX;
    self->playerY = playerY;
    self->playerA = playerA;
}

// (playerX, playerY) — 8.8 fixed-point: upper 8 = tile, lower 8 = sub-tile
// (playerA) — 0–1023 = full circle (256 per quadrant)
static void RayCasterFixedTrace(RayCaster *rayCaster,
                                uint16_t screenX,
                                uint8_t *screenY,
                                uint8_t *textureNo,
                                uint8_t *textureX,
                                uint16_t *textureY,
                                uint16_t *textureStep)
{
    RayCasterFixed *self = rayCaster->derived;
    uint16_t rayAngle =
        (uint16_t) (self->playerA + LOOKUP16(g_deltaAngle, screenX));

    // Neutralize artefacts near quadrant boundaries (±2 ticks)
    switch (rayAngle % 256) {
    case 1:
    case 254:
        rayAngle--;
        break;
    case 2:
    case 255:
        rayAngle++;
        break;
    }
    rayAngle %= 1024;

    int16_t deltaX;
    int16_t deltaY;
    RayCasterFixedCalculateDistance(self->playerX, self->playerY, rayAngle,
                                    &deltaX, &deltaY, textureNo, textureX);

    // dist = ΔY·cos(playerA) + ΔX·sin(playerA) — fisheye correction
    int16_t distance = 0;
    if (self->playerA == 0) {
        distance += deltaY;
    } else if (self->playerA == 512) {
        distance -= deltaY;
    } else {
        switch (self->viewQuarter) {
        case 0:
            distance +=
                RayCasterFixedMulS(LOOKUP8(g_cos, self->viewAngle), deltaY);
            break;
        case 1:
            distance -= RayCasterFixedMulS(
                LOOKUP8(g_cos, INVERT(self->viewAngle)), deltaY);
            break;
        case 2:
            distance -=
                RayCasterFixedMulS(LOOKUP8(g_cos, self->viewAngle), deltaY);
            break;
        case 3:
            distance += RayCasterFixedMulS(
                LOOKUP8(g_cos, INVERT(self->viewAngle)), deltaY);
            break;
        }
    }

    if (self->playerA == 256) {
        distance += deltaX;
    } else if (self->playerA == 768) {
        distance -= deltaX;
    } else {
        switch (self->viewQuarter) {
        case 0:
            distance +=
                RayCasterFixedMulS(LOOKUP8(g_sin, self->viewAngle), deltaX);
            break;
        case 1:
            distance += RayCasterFixedMulS(
                LOOKUP8(g_sin, INVERT(self->viewAngle)), deltaX);
            break;
        case 2:
            distance -=
                RayCasterFixedMulS(LOOKUP8(g_sin, self->viewAngle), deltaX);
            break;
        case 3:
            distance -= RayCasterFixedMulS(
                LOOKUP8(g_sin, INVERT(self->viewAngle)), deltaX);
            break;
        }
    }

    if (distance >= MIN_DIST) {
        *textureY = 0;
        RayCasterFixedLookupHeight((distance - MIN_DIST) >> 2, screenY,
                                   textureStep);
    } else {
        *screenY = SCREEN_HEIGHT >> 1;
        *textureY = LOOKUP16(g_overflowOffset, distance);
        *textureStep = LOOKUP16(g_overflowStep, distance);
    }
}

static void RayCasterFixedDestruct(RayCaster *rayCaster)
{
    free(rayCaster->derived);
    RayCasterDestruct(rayCaster);
}
